# Day 1 - Advanced Pandas Interview Practice (Solved)

One dataframe, advanced tasks, full solutions.
This notebook is designed for interview prep and GitHub upload.

In [1]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 80)

## Create the dataframe

In [2]:
df = pd.DataFrame({
    "emp_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen", "Ian", "Jane"],
    "dept": ["Data", "Data", "Web", "Web", "Data", "ML", "ML", "Web", "Data", "ML"],
    "city": ["Bangalore", "Bangalore", "Delhi", "Delhi", "Mumbai", "Bangalore", "Mumbai", "Delhi", "Mumbai", "Bangalore"],
    "salary": [120000, 95000, 110000, 105000, 130000, 150000, 140000, 99000, 125000, 155000],
    "bonus": [10000, 8000, 12000, 7000, 15000, 20000, 18000, 6000, 14000, 22000],
    "rating": [5, 3, 4, 2, 5, 4, 5, 3, 4, 5],
    "experience": [6, 3, 5, 2, 7, 8, 6, 3, 5, 9],
    "joined": ["2020-01-15", "2021-06-10", "2019-09-23", "2022-03-01", "2018-11-12",
               "2017-07-19", "2020-08-25", "2021-01-11", "2019-05-30", "2016-12-05"],
    "skills": [
        ["python", "sql", "pandas"],
        ["python", "excel"],
        ["javascript", "react"],
        ["javascript", "css"],
        ["python", "sql", "spark"],
        ["python", "ml", "deep-learning"],
        ["python", "ml", "sql"],
        ["html", "css", "javascript"],
        ["python", "sql", "tableau"],
        ["python", "ml", "nlp"]
    ],
    "projects": [
        [{"name": "fraud", "hours": 120}, {"name": "churn", "hours": 80}],
        [{"name": "sales_dashboard", "hours": 60}],
        [{"name": "website_revamp", "hours": 100}],
        [{"name": "landing_page", "hours": 40}, {"name": "seo_fix", "hours": 30}],
        [{"name": "recommendation", "hours": 150}],
        [{"name": "forecasting", "hours": 200}, {"name": "vision", "hours": 90}],
        [{"name": "classification", "hours": 170}],
        [{"name": "frontend_migration", "hours": 110}],
        [{"name": "reporting", "hours": 95}, {"name": "automation", "hours": 50}],
        [{"name": "llm_search", "hours": 220}, {"name": "chatbot", "hours": 140}]
    ]
})

df["joined"] = pd.to_datetime(df["joined"])
df

   emp_id     name  dept       city  salary  bonus  rating  experience     joined                       skills                                                                   projects
0     101    Alice  Data  Bangalore  120000  10000       5           6 2020-01-15        [python, sql, pandas]          [{'name': 'fraud', 'hours': 120}, {'name': 'churn', 'hours': 80}]
1     102      Bob  Data  Bangalore   95000   8000       3           3 2021-06-10              [python, excel]                                 [{'name': 'sales_dashboard', 'hours': 60}]
2     103  Charlie   Web      Delhi  110000  12000       4           5 2019-09-23          [javascript, react]                                 [{'name': 'website_revamp', 'hours': 100}]
3     104    David   Web      Delhi  105000   7000       2           2 2022-03-01            [javascript, css]  [{'name': 'landing_page', 'hours': 40}, {'name': 'seo_fix', 'hours': 30}]
4     105      Eva  Data     Mumbai  130000  15000       5           7 2018-11-12         [python, sql, spark]                                 [{'name': 'recommendation', 'hours': 150}]
5     106    Frank    ML  Bangalore  150000  20000       4           8 2017-07-19  [python, ml, deep-learning]   [{'name': 'forecasting', 'hours': 200}, {'name': 'vision', 'hours': 90}]
6     107    Grace    ML     Mumbai  140000  18000       5           6 2020-08-25            [python, ml, sql]                                 [{'name': 'classification', 'hours': 170}]
7     108    Helen   Web      Delhi   99000   6000       3           3 2021-01-11      [html, css, javascript]                             [{'name': 'frontend_migration', 'hours': 110}]
8     109      Ian  Data     Mumbai  125000  14000       4           5 2019-05-30       [python, sql, tableau]  [{'name': 'reporting', 'hours': 95}, {'name': 'automation', 'hours': 50}]
9     110     Jane    ML  Bangalore  155000  22000       5           9 2016-12-05            [python, ml, nlp]  [{'name': 'llm_search', 'hours': 220}, {'name': 'chatbot', 'hours': 140}]

## 8. Top 2 salaries in each department

In [3]:
q8 = df.groupby("dept", group_keys=False).apply(lambda g: g.nlargest(2, "salary"))
q8[["dept", "emp_id", "name", "salary"]]

/tmp/ipykernel_2546/515327387.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  q8 = df.groupby("dept", group_keys=False).apply(lambda g: g.nlargest(2, "salary"))

   dept  emp_id     name  salary
4  Data     105      Eva  130000
8  Data     109      Ian  125000
9    ML     110     Jane  155000
5    ML     106    Frank  150000
2   Web     103  Charlie  110000
3   Web     104    David  105000

## 9. Departments with average rating above 4

In [4]:
q9 = df.groupby("dept").filter(lambda g: g["rating"].mean() > 4)
q9[["dept", "emp_id", "name", "rating"]]

   dept  emp_id   name  rating
0  Data     101  Alice       5
1  Data     102    Bob       3
4  Data     105    Eva       5
5    ML     106  Frank       4
6    ML     107  Grace       5
8  Data     109    Ian       4
9    ML     110   Jane       5

## 10. Salary range by department

In [5]:
q10 = df.groupby("dept", as_index=False).agg(
    salary_range=("salary", lambda x: x.max() - x.min())
)
q10

   dept  salary_range
0  Data         35000
1    ML         15000
2   Web         11000

## 11. Weighted compensation

In [6]:
df["total_comp"] = df["salary"] + df["bonus"]
q11 = df.groupby("dept", as_index=False).agg(
    avg_total_comp=("total_comp", "mean"),
    max_total_comp=("total_comp", "max")
)
q11

   dept  avg_total_comp  max_total_comp
0  Data   129250.000000          145000
1    ML   168333.333333          177000
2   Web   113000.000000          122000

## 12. Multi-condition performance flag

In [7]:
conditions = [
    (df["rating"] >= 5) & (df["salary"] >= 130000),
    (df["rating"] >= 4)
]
choices = ["star", "good"]
df["performance_flag"] = np.select(conditions, choices, default="average")
df[["emp_id", "name", "rating", "salary", "performance_flag"]]

   emp_id     name  rating  salary performance_flag
0     101    Alice       5  120000             good
1     102      Bob       3   95000          average
2     103  Charlie       4  110000             good
3     104    David       2  105000          average
4     105      Eva       5  130000             star
5     106    Frank       4  150000             good
6     107    Grace       5  140000             star
7     108    Helen       3   99000          average
8     109      Ian       4  125000             good
9     110     Jane       5  155000             star

## 13. Employees whose salary is above their department median

In [8]:
df["dept_median_salary"] = df.groupby("dept")["salary"].transform("median")
df["above_dept_median"] = df["salary"] > df["dept_median_salary"]
df[["emp_id", "name", "dept", "salary", "dept_median_salary", "above_dept_median"]]

   emp_id     name  dept  salary  dept_median_salary  above_dept_median
0     101    Alice  Data  120000            122500.0              False
1     102      Bob  Data   95000            122500.0              False
2     103  Charlie   Web  110000            105000.0               True
3     104    David   Web  105000            105000.0              False
4     105      Eva  Data  130000            122500.0               True
5     106    Frank    ML  150000            150000.0              False
6     107    Grace    ML  140000            150000.0              False
7     108    Helen   Web   99000            105000.0              False
8     109      Ian  Data  125000            122500.0               True
9     110     Jane    ML  155000            150000.0               True

## 14. Rank salary within each department

In [9]:
df["salary_rank_in_dept"] = df.groupby("dept")["salary"].rank(method="min", ascending=False)
df[["dept", "name", "salary", "salary_rank_in_dept"]].sort_values(["dept", "salary_rank_in_dept", "salary"], ascending=[True, True, False])

   dept     name  salary  salary_rank_in_dept
4  Data      Eva  130000                  1.0
8  Data      Ian  125000                  2.0
0  Data    Alice  120000                  3.0
1  Data      Bob   95000                  4.0
9    ML     Jane  155000                  1.0
5    ML    Frank  150000                  2.0
6    ML    Grace  140000                  3.0
2   Web  Charlie  110000                  1.0
3   Web    David  105000                  2.0
7   Web    Helen   99000                  3.0

## 15. Dense rank by rating within each department

In [10]:
df["rating_rank_dense"] = df.groupby("dept")["rating"].rank(method="dense", ascending=False)
df[["dept", "name", "rating", "rating_rank_dense"]].sort_values(["dept", "rating_rank_dense", "name"])

   dept     name  rating  rating_rank_dense
0  Data    Alice       5                1.0
4  Data      Eva       5                1.0
8  Data      Ian       4                2.0
1  Data      Bob       3                3.0
6    ML    Grace       5                1.0
9    ML     Jane       5                1.0
5    ML    Frank       4                2.0
2   Web  Charlie       4                1.0
7   Web    Helen       3                2.0
3   Web    David       2                3.0

## 16. Find employees with more than 2 skills

In [11]:
q16 = df[df["skills"].apply(len) > 2]
q16[["emp_id", "name", "dept", "skills"]]

   emp_id   name  dept                       skills
0     101  Alice  Data        [python, sql, pandas]
4     105    Eva  Data         [python, sql, spark]
5     106  Frank    ML  [python, ml, deep-learning]
6     107  Grace    ML            [python, ml, sql]
7     108  Helen   Web      [html, css, javascript]
8     109    Ian  Data       [python, sql, tableau]
9     110   Jane    ML            [python, ml, nlp]

## 17. Explode skills into rows

In [12]:
skills_long = df[["emp_id", "name", "dept", "skills"]].explode("skills").rename(columns={"skills": "skill"}).reset_index(drop=True)
skills_long.head(15)

    emp_id     name  dept          skill
0      101    Alice  Data         python
1      101    Alice  Data            sql
2      101    Alice  Data         pandas
3      102      Bob  Data         python
4      102      Bob  Data          excel
5      103  Charlie   Web     javascript
6      103  Charlie   Web          react
7      104    David   Web     javascript
8      104    David   Web            css
9      105      Eva  Data         python
10     105      Eva  Data            sql
11     105      Eva  Data          spark
12     106    Frank    ML         python
13     106    Frank    ML             ml
14     106    Frank    ML  deep-learning

## 18. Count how many employees have each skill

In [13]:
q18 = skills_long["skill"].value_counts().rename_axis("skill").reset_index(name="employee_count")
q18

            skill  employee_count
0          python               7
1             sql               4
2      javascript               3
3              ml               3
4             css               2
5           excel               1
6          pandas               1
7           react               1
8           spark               1
9   deep-learning               1
10           html               1
11        tableau               1
12            nlp               1

## 19. Department-wise unique skill count

In [14]:
q19 = skills_long.groupby("dept", as_index=False).agg(unique_skill_count=("skill", "nunique"))
q19

   dept  unique_skill_count
0  Data                   6
1    ML                   5
2   Web                   4

## 20. Find employees who have both python and sql

In [15]:
q20 = df[df["skills"].apply(lambda x: {"python", "sql"}.issubset(set(x)))]
q20[["emp_id", "name", "dept", "skills"]]

   emp_id   name  dept                  skills
0     101  Alice  Data   [python, sql, pandas]
4     105    Eva  Data    [python, sql, spark]
6     107  Grace    ML       [python, ml, sql]
8     109    Ian  Data  [python, sql, tableau]

## 21. Explode projects into rows

In [16]:
projects_long = df[["emp_id", "name", "dept", "projects"]].explode("projects").reset_index(drop=True)
projects_long.head(12)

    emp_id     name  dept                                      projects
0      101    Alice  Data               {'name': 'fraud', 'hours': 120}
1      101    Alice  Data                {'name': 'churn', 'hours': 80}
2      102      Bob  Data      {'name': 'sales_dashboard', 'hours': 60}
3      103  Charlie   Web      {'name': 'website_revamp', 'hours': 100}
4      104    David   Web         {'name': 'landing_page', 'hours': 40}
5      104    David   Web              {'name': 'seo_fix', 'hours': 30}
6      105      Eva  Data      {'name': 'recommendation', 'hours': 150}
7      106    Frank    ML         {'name': 'forecasting', 'hours': 200}
8      106    Frank    ML               {'name': 'vision', 'hours': 90}
9      107    Grace    ML      {'name': 'classification', 'hours': 170}
10     108    Helen   Web  {'name': 'frontend_migration', 'hours': 110}
11     109      Ian  Data            {'name': 'reporting', 'hours': 95}

## 22. Flatten project dictionaries

In [17]:
project_details = pd.json_normalize(projects_long["projects"]).rename(columns={"name": "project_name"})
projects_flat = pd.concat([projects_long.drop(columns="projects"), project_details], axis=1)
projects_flat.head(12)

    emp_id     name  dept        project_name  hours
0      101    Alice  Data               fraud    120
1      101    Alice  Data               churn     80
2      102      Bob  Data     sales_dashboard     60
3      103  Charlie   Web      website_revamp    100
4      104    David   Web        landing_page     40
5      104    David   Web             seo_fix     30
6      105      Eva  Data      recommendation    150
7      106    Frank    ML         forecasting    200
8      106    Frank    ML              vision     90
9      107    Grace    ML      classification    170
10     108    Helen   Web  frontend_migration    110
11     109      Ian  Data           reporting     95

## 23. Total project hours per employee

In [18]:
q23 = projects_flat.groupby(["emp_id", "name"], as_index=False).agg(total_project_hours=("hours", "sum"))
q23.sort_values("total_project_hours", ascending=False)

   emp_id     name  total_project_hours
9     110     Jane                  360
5     106    Frank                  290
0     101    Alice                  200
6     107    Grace                  170
4     105      Eva                  150
8     109      Ian                  145
7     108    Helen                  110
2     103  Charlie                  100
3     104    David                   70
1     102      Bob                   60

## 24. Department-wise total project hours

In [19]:
q24 = projects_flat.groupby("dept", as_index=False).agg(total_project_hours=("hours", "sum"))
q24

   dept  total_project_hours
0  Data                  555
1    ML                  820
2   Web                  280

## 25. Average project hours per project per department

In [20]:
q25 = projects_flat.groupby(["dept", "project_name"], as_index=False).agg(avg_project_hours=("hours", "mean"))
q25

    dept        project_name  avg_project_hours
0   Data          automation               50.0
1   Data               churn               80.0
2   Data               fraud              120.0
3   Data      recommendation              150.0
4   Data           reporting               95.0
5   Data     sales_dashboard               60.0
6     ML             chatbot              140.0
7     ML      classification              170.0
8     ML         forecasting              200.0
9     ML          llm_search              220.0
10    ML              vision               90.0
11   Web  frontend_migration              110.0
12   Web        landing_page               40.0
13   Web             seo_fix               30.0
14   Web      website_revamp              100.0

## 26. Most time-consuming project for each department

In [21]:
q26 = projects_flat.sort_values(["dept", "hours"], ascending=[True, False]).drop_duplicates("dept")
q26[["dept", "emp_id", "project_name", "hours"]]

    dept  emp_id        project_name  hours
6   Data     105      recommendation    150
13    ML     110          llm_search    220
10   Web     108  frontend_migration    110

## 27. Pivot table: average salary by dept and city

In [22]:
q27 = df.pivot_table(index="dept", columns="city", values="salary", aggfunc="mean")
q27

city  Bangalore          Delhi    Mumbai
dept
Data   107500.0            NaN  127500.0
ML     152500.0            NaN  140000.0
Web         NaN  104666.666667       NaN

## 28. Pivot table: count of employees by dept and rating

In [23]:
q28 = pd.crosstab(df["dept"], df["rating"])
q28

rating  2  3  4  5
dept
Data    0  1  1  2
ML      0  0  1  2
Web     1  1  1  0

## 29. Latest joined employee in each department

In [24]:
q29 = df.sort_values(["dept", "joined"], ascending=[True, False]).drop_duplicates("dept")
q29[["dept", "emp_id", "name", "joined"]]

   dept  emp_id   name     joined
1  Data     102    Bob 2021-06-10
6    ML     107  Grace 2020-08-25
3   Web     104  David 2022-03-01

## 30. Year-wise joining count

In [25]:
q30 = df.assign(join_year=df["joined"].dt.year).groupby("join_year", as_index=False).agg(employee_count=("emp_id", "count"))
q30

   join_year  employee_count
0       2016               1
1       2017               1
2       2018               1
3       2019               2
4       2020               2
5       2021               2
6       2022               1

## 31. Employees above city average salary

In [26]:
df["city_avg_salary"] = df.groupby("city")["salary"].transform("mean")
df["above_city_avg_salary"] = df["salary"] > df["city_avg_salary"]
df[["emp_id", "name", "city", "salary", "city_avg_salary", "above_city_avg_salary"]]

   emp_id     name       city  salary  city_avg_salary  above_city_avg_salary
0     101    Alice  Bangalore  120000    130000.000000                  False
1     102      Bob  Bangalore   95000    130000.000000                  False
2     103  Charlie      Delhi  110000    104666.666667                   True
3     104    David      Delhi  105000    104666.666667                   True
4     105      Eva     Mumbai  130000    131666.666667                  False
5     106    Frank  Bangalore  150000    130000.000000                   True
6     107    Grace     Mumbai  140000    131666.666667                   True
7     108    Helen      Delhi   99000    104666.666667                  False
8     109      Ian     Mumbai  125000    131666.666667                  False
9     110     Jane  Bangalore  155000    130000.000000                   True

## 32. Employees who are top earners in both city and department

In [27]:
df["city_max_salary"] = df.groupby("city")["salary"].transform("max")
df["dept_max_salary"] = df.groupby("dept")["salary"].transform("max")
q32 = df[(df["salary"] == df["city_max_salary"]) & (df["salary"] == df["dept_max_salary"])]
q32[["emp_id", "name", "dept", "city", "salary"]]

   emp_id     name dept       city  salary
2     103  Charlie  Web      Delhi  110000
9     110     Jane   ML  Bangalore  155000

## 33. Conditional department summary

In [28]:
q33 = df.groupby("dept", as_index=False).agg(
    employees_salary_gt_120k=("salary", lambda x: (x > 120000).sum()),
    employees_bonus_ge_15k=("bonus", lambda x: (x >= 15000).sum()),
    avg_rating_exp_ge_5=("rating", lambda x: x[df.loc[x.index, "experience"] >= 5].mean())
)
q33

   dept  employees_salary_gt_120k  employees_bonus_ge_15k  avg_rating_exp_ge_5
0  Data                         2                       1             4.666667
1    ML                         3                       3             4.666667
2   Web                         0                       0             4.000000

## 34. Department skill heat problem: top 2 most common skills

In [29]:
skill_counts = skills_long.groupby(["dept", "skill"], as_index=False).size().rename(columns={"size": "count"})
q34 = skill_counts.sort_values(["dept", "count", "skill"], ascending=[True, False, True]).groupby("dept", group_keys=False).head(2)
q34

    dept       skill  count
2   Data      python      4
4   Data         sql      3
7     ML          ml      3
9     ML      python      3
13   Web  javascript      3
11   Web         css      2

## 35. Complex final department summary

In [30]:
# normal department summary
base_summary = df.groupby("dept", as_index=False).agg(
    employee_count=("emp_id", "count"),
    avg_salary=("salary", "mean"),
    avg_bonus=("bonus", "mean"),
    avg_rating=("rating", "mean"),
    high_performer_count=("rating", lambda x: (x >= 4).sum())
)

# employees with python skill
python_skill_count = (
    skills_long.assign(has_python=lambda x: x["skill"].eq("python"))
    .groupby(["dept", "emp_id"], as_index=False)["has_python"].max()
    .groupby("dept", as_index=False)
    .agg(python_skill_employee_count=("has_python", "sum"))
)

# project hour summaries
project_summary = projects_flat.groupby("dept", as_index=False).agg(
    total_project_hours=("hours", "sum"),
    max_single_project_hours=("hours", "max")
)

q35 = (
    base_summary
    .merge(python_skill_count, on="dept", how="left")
    .merge(project_summary, on="dept", how="left")
)
q35

   dept  employee_count     avg_salary     avg_bonus  avg_rating  high_performer_count  python_skill_employee_count  total_project_hours  max_single_project_hours
0  Data               4  117500.000000  11750.000000    4.250000                     3                            4                  555                       150
1    ML               3  148333.333333  20000.000000    4.666667                     3                            3                  820                       220
2   Web               3  104666.666667   8333.333333    3.000000                     1                            0                  280                       110

## Notes

- `agg` returns one row per group.
- `transform` returns the same number of rows as the original dataframe.
- `filter` keeps or removes whole groups.
- `explode` turns list values into separate rows.
- `json_normalize` flattens dictionaries into columns.